In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd       
import numpy as np        

In [3]:
path = '/content/drive/MyDrive/data.csv'  # path of the dataset 

df = pd.read_csv(path)  # reads data and stores as dataframe

In [4]:
df

passenger_id  pclass  ...                 home.dest survived
0            1216       3  ...                       NaN        1
1             699       3  ...                   Croatia        0
2            1267       3  ...                       NaN        0
3             449       2  ...      Cornwall / Akron, OH        1
4             576       2  ...  Barre, Co Washington, VT        0
..            ...     ...  ...                       ...      ...
845           158       1  ...       London / Birmingham        0
846           174       1  ...               Buffalo, NY        0
847           467       2  ...        Moscow / Bronx, NY        1
848          1112       3  ...                       NaN        0
849           425       2  ...                 Bronx, NY        0

[850 rows x 15 columns]

In [5]:
df.shape

(850, 15)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 850 entries, 0 to 849
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   passenger_id  850 non-null    int64  
 1   pclass        850 non-null    int64  
 2   name          850 non-null    object 
 3   sex           850 non-null    object 
 4   age           676 non-null    float64
 5   sibsp         850 non-null    int64  
 6   parch         850 non-null    int64  
 7   ticket        850 non-null    object 
 8   fare          849 non-null    float64
 9   cabin         191 non-null    object 
 10  embarked      849 non-null    object 
 11  boat          308 non-null    object 
 12  body          73 non-null     float64
 13  home.dest     464 non-null    object 
 14  survived      850 non-null    int64  
dtypes: float64(3), int64(5), object(7)
memory usage: 99.7+ KB


In [7]:
df['pclass'].unique()

array([3, 2, 1])

In [8]:
df['sibsp'].unique()

array([0, 1, 2, 8, 5, 4, 3])

In [9]:
df['parch'].unique()

array([0, 1, 3, 2, 9, 4, 6, 5])

In [10]:
df['cabin'].unique()

array([nan, 'C82', 'D15', 'C50', 'E33', 'B57 B59 B63 B66', 'E34', 'C83',
       'C125', 'B82 B84', 'B96 B98', 'B51 B53 B55', 'C132', 'C31', 'C68',
       'B94', 'F E46', 'C126', 'D34', 'B28', 'C65', 'B52 B54 B56', 'D17',
       'C86', 'C7', 'E25', 'E17', 'D56', 'A9', 'B26', 'C91', 'B5', 'D',
       'A23', 'C22 C26', 'C124', 'E63', 'B35', 'B18', 'C6', 'B49', 'B19',
       'G6', 'D35', 'C23 C25 C27', 'C62 C64', 'B73', 'E12', 'B41', 'A20',
       'B69', 'C78', 'A14', 'D26', 'C51', 'B79', 'E52', 'C49', 'C104',
       'B61', 'D43', 'D48', 'C123', 'A7', 'D47', 'D49', 'B80', 'A29',
       'F38', 'B58 B60', 'A34', 'D33', 'D20', 'F G63', 'T', 'A6',
       'C55 C57', 'B38', 'E49', 'F4', 'E121', 'C85', 'C87', 'B86', 'B102',
       'C111', 'D22', 'B22', 'B77', 'B50', 'B30', 'E36', 'F33', 'E60',
       'B39', 'C118', 'D21', 'F2', 'E39 E41', 'E101', 'A32', 'D38',
       'C101', 'C54', 'C106', 'C32', 'D36', 'E50', 'D40', 'C30', 'C52',
       'C130', 'C80', 'F G73', 'E10', 'B10', 'B24', 'C2', 'D28', '

In [11]:
df['embarked'].unique()

array(['Q', 'S', 'C', nan], dtype=object)

In [12]:
df['boat'].unique()

array(['13', nan, '4', '10', 'C', '8', '7', '16', '6', 'A', '15', '9',
       '14', '3', '11', '12', '2', '5 7', '5 9', 'B', '5', 'D', '1',
       'C D', '13 15', '13 15 B', '15 16'], dtype=object)

In [13]:
df['body'].unique()

array([ nan, 173., 190.,  38.,  32., 176.,  47.,  45., 110., 328., 196.,
        97.,  69., 312., 147., 135.,   9., 275.,  68.,  14., 305., 181.,
       232., 245., 124., 292., 209., 295., 206., 169., 166.,  37., 260.,
         4., 148., 103., 189., 122., 293.,  58., 286., 261.,  67., 201.,
       121.,  96., 327., 108., 236.,  75., 269.,   7., 234.,  81., 156.,
       155., 119.,  70., 306.,  62.,  89., 149., 208., 309., 307.,  53.,
       197., 283.,  16., 304., 263., 314., 258.,  19.])

In [15]:
df['home.dest'].unique()

array([nan, 'Croatia', 'Cornwall / Akron, OH', 'Barre, Co Washington, VT',
       'Finland / Washington, DC', 'Elkins Park, PA', 'Philadelphia, PA',
       'Mt Airy, Philadelphia, PA', 'East Providence, RI',
       'Weston-Super-Mare / Moose Jaw, SK',
       'St Leonards-on-Sea, England Ohio', 'Somerset / Bernardsville, NJ',
       'London Skanteales, NY', 'Hornsey, England', 'Plymouth, England',
       'New York, NY', 'Bristol, England Cleveland, OH',
       'Cornwall / Camden, NJ', 'Haverford, PA / Cooperstown, NY',
       'Tuxedo Park, NY', 'Bridgerule, Devon', 'West Hoboken, NJ',
       'Plymouth, Devon / Detroit, MI', 'Greenwich, CT', 'Ireland',
       'Indianapolis, IN', 'Bryn Mawr, PA',
       'Germantown, Philadelphia, PA', 'London Brooklyn, NY',
       'Co Sligo, Ireland Hartford, CT', 'Devon, England Wichita, KS',
       'Huntington, WV', 'Sittingbourne, England / San Diego, CA',
       'Harrow-on-the-Hill, Middlesex', 'London',
       'Strood, Kent, England Detroit, MI', 'Bu

In [16]:
df.drop(labels = {'passenger_id', 'name', 'ticket', 'fare', 'cabin' , 'boat', 'body', 'home.dest'} , axis = 1 , inplace = True)
df

pclass     sex   age  sibsp  parch embarked  survived
0         3  female   NaN      0      0        Q         1
1         3    male  38.0      0      0        S         0
2         3  female  30.0      1      1        S         0
3         2  female  54.0      1      3        S         1
4         2    male  40.0      0      0        S         0
..      ...     ...   ...    ...    ...      ...       ...
845       1    male  55.0      0      0        S         0
846       1    male  58.0      0      0        C         0
847       2  female  24.0      1      0        S         1
848       3  female   3.0      1      1        S         0
849       2    male  52.0      0      0        S         0

[850 rows x 7 columns]

In [17]:
df.isnull().sum() 

pclass        0
sex           0
age         174
sibsp         0
parch         0
embarked      1
survived      0
dtype: int64

In [18]:
df['age'].fillna(df['age'].median(), inplace=True)
df['embarked'].fillna('S', inplace=True)

In [19]:
df.isnull().sum()

pclass      0
sex         0
age         0
sibsp       0
parch       0
embarked    0
survived    0
dtype: int64

In [20]:
df

pclass     sex   age  sibsp  parch embarked  survived
0         3  female  28.0      0      0        Q         1
1         3    male  38.0      0      0        S         0
2         3  female  30.0      1      1        S         0
3         2  female  54.0      1      3        S         1
4         2    male  40.0      0      0        S         0
..      ...     ...   ...    ...    ...      ...       ...
845       1    male  55.0      0      0        S         0
846       1    male  58.0      0      0        C         0
847       2  female  24.0      1      0        S         1
848       3  female   3.0      1      1        S         0
849       2    male  52.0      0      0        S         0

[850 rows x 7 columns]

In [21]:
df['sex'] = np.where(df['sex'] == 'male' , 1 , 0 )
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["embarked"] = le.fit_transform(df["embarked"])

In [22]:
df

pclass  sex   age  sibsp  parch  embarked  survived
0         3    0  28.0      0      0         1         1
1         3    1  38.0      0      0         2         0
2         3    0  30.0      1      1         2         0
3         2    0  54.0      1      3         2         1
4         2    1  40.0      0      0         2         0
..      ...  ...   ...    ...    ...       ...       ...
845       1    1  55.0      0      0         2         0
846       1    1  58.0      0      0         0         0
847       2    0  24.0      1      0         2         1
848       3    0   3.0      1      1         2         0
849       2    1  52.0      0      0         2         0

[850 rows x 7 columns]

In [23]:
df['age'] = df['age']/df['age'].max()

In [24]:
X = df.drop('survived' , axis = 1) 
Y = df['survived']

In [25]:
from sklearn import model_selection
X_train , X_test , Y_train, Y_test = model_selection.train_test_split(X , Y ,test_size = 0.2, shuffle = True , stratify=Y  )

In [26]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [27]:
from sklearn.tree import DecisionTreeClassifier
clfr = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
clfr.fit(X_train, Y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [28]:
Y_pred = clfr.predict(X_test)

In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(Y_test, Y_pred)
print(cm)
accuracy_score(Y_test, Y_pred)

[[95 12]
 [16 47]]


0.8352941176470589